version: '3.8'

services:
  api:
    container_name: app-backend
    build: ./backend/
    volumes:
      - ./backend:/app/backend/
      - sock_volume:/sock/
    networks:
      - web_network
    ports:
      - "8000:8000"  # Adjust the port number as needed
    stdin_open: true
    tty: true
  web:
    container_name: app-frontend
    build: ./frontend/
    volumes:
      - ./frontend:/app/frontend/
      - static_volume:/app/frontend/
    networks:
      - web_network
    ports:
      - '3000:3000'  # Adjust the port number as needed
    stdin_open: true
    tty: true
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/frontend/
      - sock_volume:/sock/
    ports:
      - "80:80"  # Adjust the port number as needed
      - "5000:3000"
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  static_volume:
  sock_volume:
